export const s_patients = [
  {
    id: 1,
    name: "John Doe",
    age: 34,
    gender: "Male",
    photo: "https://randomuser.me/api/portraits/men/32.jpg",
    contact: "+91 9876543210",
    emergencyContact: "+91 9123456789",
    chiefComplaint: "Fever and cough",
    symptoms: "High fever, dry cough, fatigue",
    vitals: {
      temperature: 101.2,
      bp: "130/85",
      heartRate: 98,
      respRate: 18,
      spo2: 97,
      weight: 72,
      height: 175,
    },
    medications: [
      { name: "Paracetamol", dosage: "500mg", frequency: "Twice a day" },
      { name: "Cough Syrup", dosage: "10ml", frequency: "Thrice a day" },
    ],
    allergies: ["Penicillin"],
    chronic: ["Hypertension"],
    surgeries: ["Appendectomy (2015)"],
    insurance: "MediCare Plus (ID: MC123456)",
    familyHistory: "Father: Diabetes, Mother: Hypertension",
    lifestyle: "Non-smoker, Occasional alcohol",
    medicalHistory: [
      {
        date: "2024-06-15",
        summary: "Routine checkup. All vitals normal.",
        details: "No complaints. BP slightly elevated.",
      },
    ],
    medicalRecords: [
      {
        id: 1,
        title: "Blood Test Results",
        category: "Lab Results",
        date: "2024-12-15",
        doctorName: "Dr. Sarah Johnson",
        hospital: "City General Hospital",
        description: "Complete blood count and lipid profile",
        fileType: "pdf",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 28,
    gender: "Female",
    photo: "https://randomuser.me/api/portraits/women/44.jpg",
    contact: "+91 9988776655",
    emergencyContact: "+91 8877665544",
    chiefComplaint: "Headache",
    symptoms: "Persistent headache, mild nausea",
    vitals: {
      temperature: 98.6,
      bp: "120/80",
      heartRate: 76,
      respRate: 16,
      spo2: 99,
      weight: 60,
      height: 165,
    },
    medications: [
      { name: "Ibuprofen", dosage: "400mg", frequency: "Once a day" },
    ],
    allergies: [],
    chronic: [],
    surgeries: [],
    insurance: "HealthSecure (ID: HS987654)",
    familyHistory: "No significant history",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-06-01",
        summary: "Migraine episode, prescribed medication.",
        details: "Advised to avoid screen time.",
      },
    ],
    medicalRecords: [
      {
        id: 2,
        title: "MRI Brain",
        category: "X-Ray/Imaging",
        date: "2024-12-10",
        doctorName: "Dr. Michael Chen",
        hospital: "Metro Medical Center",
        description: "Routine MRI brain scan",
        fileType: "image",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Brown",
    age: 41,
    gender: "Female",
    photo: "https://randomuser.me/api/portraits/women/65.jpg",
    contact: "+91 9123456780",
    emergencyContact: "+91 9988776655",
    chiefComplaint: "Back pain",
    symptoms: "Lower back pain, stiffness",
    vitals: {
      temperature: 98.7,
      bp: "125/82",
      heartRate: 80,
      respRate: 17,
      spo2: 98,
      weight: 68,
      height: 162,
    },
    medications: [
      { name: "Ibuprofen", dosage: "400mg", frequency: "Twice a day" },
    ],
    allergies: ["Latex"],
    chronic: ["Arthritis"],
    surgeries: ["None"],
    insurance: "CarePlus (ID: CP112233)",
    familyHistory: "Mother: Arthritis",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-05-20",
        summary: "Back pain, prescribed physiotherapy.",
        details: "Advised regular exercise.",
      },
    ],
    medicalRecords: [
      {
        id: 3,
        title: "Spine X-Ray",
        category: "X-Ray/Imaging",
        date: "2024-11-18",
        doctorName: "Dr. Alex Turner",
        hospital: "City General Hospital",
        description: "Lumbar spine x-ray for back pain",
        fileType: "image",
      },
    ],
  },
  {
    id: 4,
    name: "Bob Lee",
    age: 36,
    gender: "Male",
    photo: "https://randomuser.me/api/portraits/men/45.jpg",
    contact: "+91 9000000004",
    emergencyContact: "+91 9000000005",
    chiefComplaint: "Routine checkup",
    symptoms: "No symptoms",
    vitals: {
      temperature: 98.4,
      bp: "120/80",
      heartRate: 72,
      respRate: 16,
      spo2: 99,
      weight: 75,
      height: 178,
    },
    medications: [
      { name: "Multivitamin", dosage: "1 tablet", frequency: "Once a day" },
    ],
    allergies: ["None"],
    chronic: ["None"],
    surgeries: ["None"],
    insurance: "MediAssist (ID: MA100004)",
    familyHistory: "No significant history",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-04-10",
        summary: "Annual physical exam.",
        details: "All parameters within normal limits.",
      },
    ],
    medicalRecords: [
      {
        id: 4,
        title: "Annual Physical Report",
        category: "Medical Report",
        date: "2024-04-10",
        doctorName: "Dr. Priya Singh",
        hospital: "Wellness Clinic",
        description: "Routine annual checkup report.",
        fileType: "pdf",
      },
    ],
  },
  {
    id: 5,
    name: "Charlie Kim",
    age: 29,
    gender: "Male",
    photo: "https://randomuser.me/api/portraits/men/46.jpg",
    contact: "+91 9000000006",
    emergencyContact: "+91 9000000007",
    chiefComplaint: "Allergy",
    symptoms: "Sneezing, runny nose",
    vitals: {
      temperature: 98.5,
      bp: "118/76",
      heartRate: 74,
      respRate: 17,
      spo2: 98,
      weight: 68,
      height: 172,
    },
    medications: [
      { name: "Cetirizine", dosage: "10mg", frequency: "Once a day" },
    ],
    allergies: ["Pollen"],
    chronic: ["Allergic Rhinitis"],
    surgeries: ["None"],
    insurance: "CareFirst (ID: CF100005)",
    familyHistory: "Mother: Asthma",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-03-15",
        summary: "Allergy symptoms, prescribed antihistamine.",
        details: "Advised to avoid pollen exposure.",
      },
    ],
    medicalRecords: [
      {
        id: 5,
        title: "Allergy Test Report",
        category: "Lab Results",
        date: "2024-03-14",
        doctorName: "Dr. Rakesh Mehta",
        hospital: "Allergy Center",
        description: "Skin prick test for common allergens.",
        fileType: "pdf",
      },
    ],
  },
  {
    id: 6,
    name: "Night Owl",
    age: 40,
    gender: "Male",
    photo: "https://randomuser.me/api/portraits/men/47.jpg",
    contact: "+91 9000000008",
    emergencyContact: "+91 9000000009",
    chiefComplaint: "Insomnia",
    symptoms: "Difficulty sleeping",
    vitals: {
      temperature: 98.6,
      bp: "122/80",
      heartRate: 70,
      respRate: 16,
      spo2: 98,
      weight: 80,
      height: 180,
    },
    medications: [
      { name: "Melatonin", dosage: "3mg", frequency: "Once at night" },
    ],
    allergies: ["None"],
    chronic: ["Insomnia"],
    surgeries: ["None"],
    insurance: "SleepCare (ID: SC100006)",
    familyHistory: "Father: Hypertension",
    lifestyle: "Smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-02-20",
        summary: "Sleep disturbance, started melatonin.",
        details: "Advised sleep hygiene and regular schedule.",
      },
    ],
    medicalRecords: [
      {
        id: 6,
        title: "Sleep Study Report",
        category: "Medical Report",
        date: "2024-02-18",
        doctorName: "Dr. Anjali Rao",
        hospital: "Sleep Clinic",
        description: "Polysomnography for sleep disorder diagnosis.",
        fileType: "pdf",
      },
    ],
  },
  {
    id: 7,
    name: "Diana Prince",
    age: 35,
    gender: "Female",
    photo: "https://randomuser.me/api/portraits/women/47.jpg",
    contact: "+91 9000000010",
    emergencyContact: "+91 9000000011",
    chiefComplaint: "Fatigue",
    symptoms: "Tiredness, low energy",
    vitals: {
      temperature: 98.3,
      bp: "119/77",
      heartRate: 75,
      respRate: 16,
      spo2: 99,
      weight: 62,
      height: 168,
    },
    medications: [
      { name: "Iron Supplement", dosage: "100mg", frequency: "Once a day" },
    ],
    allergies: ["None"],
    chronic: ["Anemia"],
    surgeries: ["None"],
    insurance: "HealthPlus (ID: HP100007)",
    familyHistory: "Mother: Diabetes",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-01-10",
        summary: "Fatigue, diagnosed with mild anemia.",
        details: "Started iron supplementation.",
      },
    ],
    medicalRecords: [
      {
        id: 7,
        title: "CBC Report",
        category: "Lab Results",
        date: "2024-01-09",
        doctorName: "Dr. Suresh Nair",
        hospital: "City Lab",
        description: "Complete blood count for anemia diagnosis.",
        fileType: "pdf",
      },
    ],
  },
  {
    id: 8,
    name: "Grace Hall",
    age: 50,
    gender: "Female",
    photo: "https://randomuser.me/api/portraits/women/48.jpg",
    contact: "+91 9000000012",
    emergencyContact: "+91 9000000013",
    chiefComplaint: "Hypertension follow-up",
    symptoms: "No symptoms",
    vitals: {
      temperature: 98.5,
      bp: "140/90",
      heartRate: 78,
      respRate: 18,
      spo2: 97,
      weight: 70,
      height: 160,
    },
    medications: [
      { name: "Amlodipine", dosage: "5mg", frequency: "Once a day" },
    ],
    allergies: ["None"],
    chronic: ["Hypertension"],
    surgeries: ["None"],
    insurance: "SeniorCare (ID: SC100008)",
    familyHistory: "Father: Hypertension",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-05-01",
        summary: "Hypertension follow-up, BP controlled.",
        details: "Continue current medication.",
      },
    ],
    medicalRecords: [
      {
        id: 8,
        title: "BP Monitoring Chart",
        category: "Medical Report",
        date: "2024-04-30",
        doctorName: "Dr. Kavita Sharma",
        hospital: "Senior Clinic",
        description: "Blood pressure log for 1 month.",
        fileType: "pdf",
      },
    ],
  },
  {
    id: 9,
    name: "Henry Ford",
    age: 60,
    gender: "Male",
    photo: "https://randomuser.me/api/portraits/men/48.jpg",
    contact: "+91 9000000014",
    emergencyContact: "+91 9000000015",
    chiefComplaint: "Arthritis",
    symptoms: "Joint pain",
    vitals: {
      temperature: 98.6,
      bp: "130/85",
      heartRate: 80,
      respRate: 18,
      spo2: 98,
      weight: 85,
      height: 170,
    },
    medications: [
      { name: "Ibuprofen", dosage: "400mg", frequency: "Twice a day" },
    ],
    allergies: ["None"],
    chronic: ["Arthritis"],
    surgeries: ["Knee replacement (2020)"],
    insurance: "ElderCare (ID: EC100009)",
    familyHistory: "Mother: Arthritis",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-03-10",
        summary: "Arthritis pain, prescribed NSAIDs.",
        details: "Advised physiotherapy.",
      },
    ],
    medicalRecords: [
      {
        id: 9,
        title: "Knee X-Ray",
        category: "X-Ray/Imaging",
        date: "2024-03-09",
        doctorName: "Dr. Rajiv Kumar",
        hospital: "Ortho Center",
        description: "X-ray for arthritis assessment.",
        fileType: "image",
      },
    ],
  },
  {
    id: 10,
    name: "Ivy Lane",
    age: 27,
    gender: "Female",
    photo: "https://randomuser.me/api/portraits/women/49.jpg",
    contact: "+91 9000000016",
    emergencyContact: "+91 9000000017",
    chiefComplaint: "Routine checkup",
    symptoms: "No symptoms",
    vitals: {
      temperature: 98.4,
      bp: "118/76",
      heartRate: 72,
      respRate: 16,
      spo2: 99,
      weight: 55,
      height: 162,
    },
    medications: [
      { name: "Multivitamin", dosage: "1 tablet", frequency: "Once a day" },
    ],
    allergies: ["None"],
    chronic: ["None"],
    surgeries: ["None"],
    insurance: "YoungCare (ID: YC100010)",
    familyHistory: "No significant history",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-06-01",
        summary: "Routine checkup, all normal.",
        details: "Advised healthy diet and exercise.",
      },
    ],
    medicalRecords: [
      {
        id: 10,
        title: "Annual Health Report",
        category: "Medical Report",
        date: "2024-05-30",
        doctorName: "Dr. Neha Gupta",
        hospital: "Wellness Clinic",
        description: "Comprehensive health checkup report.",
        fileType: "pdf",
      },
    ],
  },
  {
    id: 11,
    name: "Sam Carter",
    age: 38,
    gender: "Male",
    photo: "https://randomuser.me/api/portraits/men/49.jpg",
    contact: "+91 9000000018",
    emergencyContact: "+91 9000000019",
    chiefComplaint: "Knee pain",
    symptoms: "Pain while walking",
    vitals: {
      temperature: 98.7,
      bp: "124/80",
      heartRate: 74,
      respRate: 17,
      spo2: 98,
      weight: 78,
      height: 175,
    },
    medications: [
      { name: "Paracetamol", dosage: "500mg", frequency: "Twice a day" },
    ],
    allergies: ["None"],
    chronic: ["None"],
    surgeries: ["None"],
    insurance: "ActiveCare (ID: AC100011)",
    familyHistory: "Father: Arthritis",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-04-15",
        summary: "Knee pain, prescribed rest and medication.",
        details: "Advised physiotherapy.",
      },
    ],
    medicalRecords: [
      {
        id: 11,
        title: "Knee MRI",
        category: "X-Ray/Imaging",
        date: "2024-04-14",
        doctorName: "Dr. Sunil Joshi",
        hospital: "Ortho Center",
        description: "MRI for knee pain assessment.",
        fileType: "image",
      },
    ],
  },
  {
    id: 12,
    name: "Eve Adams",
    age: 32,
    gender: "Female",
    photo: "https://randomuser.me/api/portraits/women/50.jpg",
    contact: "+91 9000000020",
    emergencyContact: "+91 9000000021",
    chiefComplaint: "Fever",
    symptoms: "Mild fever, headache",
    vitals: {
      temperature: 99.1,
      bp: "120/80",
      heartRate: 80,
      respRate: 18,
      spo2: 98,
      weight: 60,
      height: 165,
    },
    medications: [
      { name: "Paracetamol", dosage: "500mg", frequency: "Twice a day" },
    ],
    allergies: ["None"],
    chronic: ["None"],
    surgeries: ["None"],
    insurance: "HealthFirst (ID: HF100012)",
    familyHistory: "Mother: Hypertension",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-05-10",
        summary: "Fever, prescribed paracetamol.",
        details: "Advised rest and fluids.",
      },
    ],
    medicalRecords: [
      {
        id: 12,
        title: "Fever Panel",
        category: "Lab Results",
        date: "2024-05-09",
        doctorName: "Dr. Amit Shah",
        hospital: "City Lab",
        description: "Blood tests for fever diagnosis.",
        fileType: "pdf",
      },
    ],
  },
  {
    id: 13,
    name: "Frank Moore",
    age: 45,
    gender: "Male",
    photo: "https://randomuser.me/api/portraits/men/50.jpg",
    contact: "+91 9000000022",
    emergencyContact: "+91 9000000023",
    chiefComplaint: "Chest pain",
    symptoms: "Mild chest pain",
    vitals: {
      temperature: 98.8,
      bp: "130/85",
      heartRate: 82,
      respRate: 18,
      spo2: 97,
      weight: 85,
      height: 180,
    },
    medications: [
      { name: "Aspirin", dosage: "75mg", frequency: "Once a day" },
    ],
    allergies: ["None"],
    chronic: ["Hypertension"],
    surgeries: ["None"],
    insurance: "SecureCare (ID: SC100013)",
    familyHistory: "Father: Heart Disease",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-03-20",
        summary: "Chest pain, ECG normal.",
        details: "Advised to monitor symptoms.",
      },
    ],
    medicalRecords: [
      {
        id: 13,
        title: "ECG Report",
        category: "Lab Results",
        date: "2024-03-19",
        doctorName: "Dr. Meena Patel",
        hospital: "Heart Center",
        description: "ECG for chest pain evaluation.",
        fileType: "pdf",
      },
    ],
  },
  {
    id: 14,
    name: "Jack Frost",
    age: 31,
    gender: "Male",
    photo: "https://randomuser.me/api/portraits/men/51.jpg",
    contact: "+91 9000000024",
    emergencyContact: "+91 9000000025",
    chiefComplaint: "Cold",
    symptoms: "Sneezing, runny nose",
    vitals: {
      temperature: 98.5,
      bp: "118/76",
      heartRate: 70,
      respRate: 16,
      spo2: 99,
      weight: 70,
      height: 175,
    },
    medications: [
      { name: "Cetirizine", dosage: "10mg", frequency: "Once a day" },
    ],
    allergies: ["Dust"],
    chronic: ["None"],
    surgeries: ["None"],
    insurance: "FrostCare (ID: FC100014)",
    familyHistory: "Mother: Asthma",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-02-05",
        summary: "Cold symptoms, prescribed antihistamine.",
        details: "Advised steam inhalation.",
      },
    ],
    medicalRecords: [
      {
        id: 14,
        title: "Allergy Panel",
        category: "Lab Results",
        date: "2024-02-04",
        doctorName: "Dr. Rakesh Mehta",
        hospital: "Allergy Center",
        description: "Blood test for allergy markers.",
        fileType: "pdf",
      },
    ],
  },
  {
    id: 15,
    name: "Karen Page",
    age: 29,
    gender: "Female",
    photo: "https://randomuser.me/api/portraits/women/51.jpg",
    contact: "+91 9000000026",
    emergencyContact: "+91 9000000027",
    chiefComplaint: "Migraine",
    symptoms: "Headache, nausea",
    vitals: {
      temperature: 98.6,
      bp: "120/80",
      heartRate: 76,
      respRate: 16,
      spo2: 99,
      weight: 58,
      height: 160,
    },
    medications: [
      { name: "Ibuprofen", dosage: "400mg", frequency: "Once a day" },
    ],
    allergies: ["None"],
    chronic: ["Migraine"],
    surgeries: ["None"],
    insurance: "PageCare (ID: PC100015)",
    familyHistory: "Father: Migraine",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-01-20",
        summary: "Migraine attack, prescribed pain relief.",
        details: "Advised to avoid triggers.",
      },
    ],
    medicalRecords: [
      {
        id: 15,
        title: "MRI Brain",
        category: "X-Ray/Imaging",
        date: "2024-01-19",
        doctorName: "Dr. Michael Chen",
        hospital: "Metro Medical Center",
        description: "MRI for migraine evaluation.",
        fileType: "image",
      },
    ],
  },
  {
    id: 16,
    name: "Leo King",
    age: 37,
    gender: "Male",
    photo: "https://randomuser.me/api/portraits/men/52.jpg",
    contact: "+91 9000000028",
    emergencyContact: "+91 9000000029",
    chiefComplaint: "Routine checkup",
    symptoms: "No symptoms",
    vitals: {
      temperature: 98.4,
      bp: "120/80",
      heartRate: 72,
      respRate: 16,
      spo2: 99,
      weight: 80,
      height: 180,
    },
    medications: [
      { name: "Multivitamin", dosage: "1 tablet", frequency: "Once a day" },
    ],
    allergies: ["None"],
    chronic: ["None"],
    surgeries: ["None"],
    insurance: "KingCare (ID: KC100016)",
    familyHistory: "No significant history",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-06-01",
        summary: "Routine checkup, all normal.",
        details: "Advised healthy diet and exercise.",
      },
    ],
    medicalRecords: [
      {
        id: 16,
        title: "Annual Health Report",
        category: "Medical Report",
        date: "2024-05-30",
        doctorName: "Dr. Neha Gupta",
        hospital: "Wellness Clinic",
        description: "Comprehensive health checkup report.",
        fileType: "pdf",
      },
    ],
  },
  {
    id: 17,
    name: "Mona Ray",
    age: 33,
    gender: "Female",
    photo: "https://randomuser.me/api/portraits/women/52.jpg",
    contact: "+91 9000000030",
    emergencyContact: "+91 9000000031",
    chiefComplaint: "Stomach ache",
    symptoms: "Abdominal pain",
    vitals: {
      temperature: 99.0,
      bp: "118/76",
      heartRate: 74,
      respRate: 17,
      spo2: 98,
      weight: 62,
      height: 165,
    },
    medications: [
      { name: "Omeprazole", dosage: "20mg", frequency: "Once a day" },
    ],
    allergies: ["None"],
    chronic: ["Gastritis"],
    surgeries: ["None"],
    insurance: "RayCare (ID: RC100017)",
    familyHistory: "Mother: Ulcer",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-04-12",
        summary: "Stomach pain, prescribed omeprazole.",
        details: "Advised bland diet.",
      },
    ],
    medicalRecords: [
      {
        id: 17,
        title: "Abdominal Ultrasound",
        category: "X-Ray/Imaging",
        date: "2024-04-11",
        doctorName: "Dr. Ritu Sharma",
        hospital: "City Hospital",
        description: "Ultrasound for abdominal pain.",
        fileType: "image",
      },
    ],
  },
  {
    id: 18,
    name: "Nina West",
    age: 26,
    gender: "Female",
    photo: "https://randomuser.me/api/portraits/women/53.jpg",
    contact: "+91 9000000032",
    emergencyContact: "+91 9000000033",
    chiefComplaint: "Cough",
    symptoms: "Dry cough",
    vitals: {
      temperature: 98.7,
      bp: "120/80",
      heartRate: 76,
      respRate: 16,
      spo2: 99,
      weight: 55,
      height: 160,
    },
    medications: [
      { name: "Cough Syrup", dosage: "10ml", frequency: "Thrice a day" },
    ],
    allergies: ["None"],
    chronic: ["None"],
    surgeries: ["None"],
    insurance: "WestCare (ID: WC100018)",
    familyHistory: "Father: Asthma",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-03-18",
        summary: "Dry cough, prescribed syrup.",
        details: "Advised steam inhalation.",
      },
    ],
    medicalRecords: [
      {
        id: 18,
        title: "Chest X-Ray",
        category: "X-Ray/Imaging",
        date: "2024-03-17",
        doctorName: "Dr. Ajay Singh",
        hospital: "Metro Medical Center",
        description: "X-ray for cough evaluation.",
        fileType: "image",
      },
    ],
  },
  {
    id: 19,
    name: "Oscar Wilde",
    age: 44,
    gender: "Male",
    photo: "https://randomuser.me/api/portraits/men/53.jpg",
    contact: "+91 9000000034",
    emergencyContact: "+91 9000000035",
    chiefComplaint: "Joint pain",
    symptoms: "Knee pain",
    vitals: {
      temperature: 98.8,
      bp: "125/80",
      heartRate: 78,
      respRate: 17,
      spo2: 98,
      weight: 85,
      height: 178,
    },
    medications: [
      { name: "Paracetamol", dosage: "500mg", frequency: "Twice a day" },
    ],
    allergies: ["None"],
    chronic: ["Arthritis"],
    surgeries: ["None"],
    insurance: "WildeCare (ID: WC100019)",
    familyHistory: "Mother: Arthritis",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-02-22",
        summary: "Knee pain, prescribed pain relief.",
        details: "Advised physiotherapy.",
      },
    ],
    medicalRecords: [
      {
        id: 19,
        title: "Knee X-Ray",
        category: "X-Ray/Imaging",
        date: "2024-02-21",
        doctorName: "Dr. Sunil Joshi",
        hospital: "Ortho Center",
        description: "X-ray for knee pain assessment.",
        fileType: "image",
      },
    ],
  },
  {
    id: 20,
    name: "Paul Young",
    age: 39,
    gender: "Male",
    photo: "https://randomuser.me/api/portraits/men/54.jpg",
    contact: "+91 9000000036",
    emergencyContact: "+91 9000000037",
    chiefComplaint: "Routine checkup",
    symptoms: "No symptoms",
    vitals: {
      temperature: 98.5,
      bp: "120/80",
      heartRate: 72,
      respRate: 16,
      spo2: 99,
      weight: 77,
      height: 175,
    },
    medications: [
      { name: "Multivitamin", dosage: "1 tablet", frequency: "Once a day" },
    ],
    allergies: ["None"],
    chronic: ["None"],
    surgeries: ["None"],
    insurance: "YoungCare (ID: YC100020)",
    familyHistory: "No significant history",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-06-01",
        summary: "Routine checkup, all normal.",
        details: "Advised healthy diet and exercise.",
      },
    ],
    medicalRecords: [
      {
        id: 20,
        title: "Annual Health Report",
        category: "Medical Report",
        date: "2024-05-30",
        doctorName: "Dr. Neha Gupta",
        hospital: "Wellness Clinic",
        description: "Comprehensive health checkup report.",
        fileType: "pdf",
      },
    ],
  },
  {
    id: 21,
    name: "Quinn Fox",
    age: 30,
    gender: "Male",
    photo: "https://randomuser.me/api/portraits/men/55.jpg",
    contact: "+91 9000000038",
    emergencyContact: "+91 9000000039",
    chiefComplaint: "Fever",
    symptoms: "High fever",
    vitals: {
      temperature: 101.0,
      bp: "120/80",
      heartRate: 90,
      respRate: 18,
      spo2: 97,
      weight: 70,
      height: 170,
    },
    medications: [
      { name: "Paracetamol", dosage: "500mg", frequency: "Twice a day" },
    ],
    allergies: ["None"],
    chronic: ["None"],
    surgeries: ["None"],
    insurance: "FoxCare (ID: FC100021)",
    familyHistory: "Mother: Hypertension",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-05-05",
        summary: "Fever, prescribed paracetamol.",
        details: "Advised rest and fluids.",
      },
    ],
    medicalRecords: [
      {
        id: 21,
        title: "Fever Panel",
        category: "Lab Results",
        date: "2024-05-04",
        doctorName: "Dr. Amit Shah",
        hospital: "City Lab",
        description: "Blood tests for fever diagnosis.",
        fileType: "pdf",
      },
    ],
  },
  {
    id: 22,
    name: "Rita Stone",
    age: 36,
    gender: "Female",
    photo: "https://randomuser.me/api/portraits/women/54.jpg",
    contact: "+91 9000000040",
    emergencyContact: "+91 9000000041",
    chiefComplaint: "Back pain",
    symptoms: "Lower back pain",
    vitals: {
      temperature: 98.7,
      bp: "125/82",
      heartRate: 80,
      respRate: 17,
      spo2: 98,
      weight: 68,
      height: 162,
    },
    medications: [
      { name: "Ibuprofen", dosage: "400mg", frequency: "Twice a day" },
    ],
    allergies: ["None"],
    chronic: ["Arthritis"],
    surgeries: ["None"],
    insurance: "StoneCare (ID: SC100022)",
    familyHistory: "Mother: Arthritis",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-04-10",
        summary: "Back pain, prescribed physiotherapy.",
        details: "Advised regular exercise.",
      },
    ],
    medicalRecords: [
      {
        id: 22,
        title: "Spine X-Ray",
        category: "X-Ray/Imaging",
        date: "2024-04-09",
        doctorName: "Dr. Alex Turner",
        hospital: "City General Hospital",
        description: "Lumbar spine x-ray for back pain",
        fileType: "image",
      },
    ],
  },
  {
    id: 23,
    name: "Steve Nash",
    age: 42,
    gender: "Male",
    photo: "https://randomuser.me/api/portraits/men/56.jpg",
    contact: "+91 9000000042",
    emergencyContact: "+91 9000000043",
    chiefComplaint: "Diabetes follow-up",
    symptoms: "No symptoms",
    vitals: {
      temperature: 98.6,
      bp: "120/80",
      heartRate: 76,
      respRate: 16,
      spo2: 99,
      weight: 80,
      height: 180,
    },
    medications: [
      { name: "Metformin", dosage: "500mg", frequency: "Twice a day" },
    ],
    allergies: ["None"],
    chronic: ["Diabetes"],
    surgeries: ["None"],
    insurance: "NashCare (ID: NC100023)",
    familyHistory: "Father: Diabetes",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-03-01",
        summary: "Diabetes follow-up, blood sugar controlled.",
        details: "Continue current medication.",
      },
    ],
    medicalRecords: [
      {
        id: 23,
        title: "Blood Sugar Report",
        category: "Lab Results",
        date: "2024-02-28",
        doctorName: "Dr. Kavita Sharma",
        hospital: "Diabetes Clinic",
        description: "Fasting and postprandial blood sugar.",
        fileType: "pdf",
      },
    ],
  },
  {
    id: 24,
    name: "Tina Bell",
    age: 27,
    gender: "Female",
    photo: "https://randomuser.me/api/portraits/women/55.jpg",
    contact: "+91 9000000044",
    emergencyContact: "+91 9000000045",
    chiefComplaint: "Cough",
    symptoms: "Dry cough",
    vitals: {
      temperature: 98.7,
      bp: "120/80",
      heartRate: 76,
      respRate: 16,
      spo2: 99,
      weight: 55,
      height: 160,
    },
    medications: [
      { name: "Cough Syrup", dosage: "10ml", frequency: "Thrice a day" },
    ],
    allergies: ["None"],
    chronic: ["None"],
    surgeries: ["None"],
    insurance: "BellCare (ID: BC100024)",
    familyHistory: "Father: Asthma",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-02-10",
        summary: "Dry cough, prescribed syrup.",
        details: "Advised steam inhalation.",
      },
    ],
    medicalRecords: [
      {
        id: 24,
        title: "Chest X-Ray",
        category: "X-Ray/Imaging",
        date: "2024-02-09",
        doctorName: "Dr. Ajay Singh",
        hospital: "Metro Medical Center",
        description: "X-ray for cough evaluation.",
        fileType: "image",
      },
    ],
  },
  {
    id: 25,
    name: "Uma Dale",
    age: 31,
    gender: "Female",
    photo: "https://randomuser.me/api/portraits/women/56.jpg",
    contact: "+91 9000000046",
    emergencyContact: "+91 9000000047",
    chiefComplaint: "Routine checkup",
    symptoms: "No symptoms",
    vitals: {
      temperature: 98.4,
      bp: "120/80",
      heartRate: 72,
      respRate: 16,
      spo2: 99,
      weight: 60,
      height: 165,
    },
    medications: [
      { name: "Multivitamin", dosage: "1 tablet", frequency: "Once a day" },
    ],
    allergies: ["None"],
    chronic: ["None"],
    surgeries: ["None"],
    insurance: "DaleCare (ID: DC100025)",
    familyHistory: "No significant history",
    lifestyle: "Non-smoker, No alcohol",
    medicalHistory: [
      {
        date: "2024-06-01",
        summary: "Routine checkup, all normal.",
        details: "Advised healthy diet and exercise.",
      },
    ],
    medicalRecords: [
      {
        id: 25,
        title: "Annual Health Report",
        category: "Medical Report",
        date: "2024-05-30",
        doctorName: "Dr. Neha Gupta",
        hospital: "Wellness Clinic",
        description: "Comprehensive health checkup report.",
        fileType: "pdf",
      },
    ],
  },
];



export const s_doctor = {
  fullName: "Dr. Priya Sharma",
  photo:
    "https://randomuser.me/api/portraits/women/68.jpg",
  gender: "Female",
  contact: {
    phone: "+91 98765 43210",
    email: "priya.sharma@cityhospital.com",
  },
  qualifications: ["MBBS", "MD (Internal Medicine)", "FACP"],
  specialization: "Cardiologist",
  subSpecialization: "Interventional Cardiology",
  experience: 15,
  hospital: "City General Hospital",
  department: "Cardiology",
  designation: "Senior Consultant",
  languages: ["English", "Hindi", "Bengali"],
  consultingHours: [
    { day: "Mon-Fri", time: "10:00 AM - 2:00 PM" },
    { day: "Sat", time: "11:00 AM - 1:00 PM" },
  ],
  location: "123, Heart Avenue, City Center, New Delhi, India",
  telemedicine: true,
  appointmentSlots: [
    "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM"
  ],
  patientsTreated: 2500,
  license: {
    number: "DL-123456",
    state: "Delhi",
  },
  boardCertifications: [
    "Medical Council of India",
    "Delhi Medical Council",
    "American Board of Internal Medicine",
  ],
  memberships: [
    "Indian Medical Association",
    "American College of Physicians",
    "Cardiological Society of India",
  ],
  publications: [
    {
      title: "Advances in Cardiac Stent Technology",
      journal: "Indian Heart Journal",
      year: 2022,
    },
    {
      title: "Managing Hypertension in Urban India",
      journal: "Journal of Clinical Medicine",
      year: 2021,
    },
  ],
  awards: [
    {
      title: "Best Cardiologist Award",
      by: "Delhi Medical Association",
      year: 2023,
    },
    {
      title: "Excellence in Patient Care",
      by: "City General Hospital",
      year: 2021,
    },
  ],
};


export const s_bookings = {
  Monday: {
    "08:00": { patientName: "John Doe", patientId: 1 },
    "09:00": { patientName: "Jane Smith", patientId: 2 },
    "10:30": { patientName: "Alice Brown", patientId: 3 },
    "13:00": { patientName: "Night Owl", patientId: 6 },
    "15:30": { patientName: "Sam Carter", patientId: 11 },
  },
  Tuesday: {
    "08:30": { patientName: "Bob Lee", patientId: 4 },
    "09:30": { patientName: "Charlie Kim", patientId: 5 },
    "11:00": { patientName: "Diana Prince", patientId: 7 },
    "14:00": { patientName: "Eve Adams", patientId: 12 },
    "16:00": { patientName: "Frank Moore", patientId: 13 },
  },
  Wednesday: {
    "08:00": { patientName: "Grace Hall", patientId: 8 },
    "09:30": { patientName: "Henry Ford", patientId: 9 },
    "12:00": { patientName: "Ivy Lane", patientId: 10 },
    "13:30": { patientName: "Jack Frost", patientId: 14 },
    "15:00": { patientName: "Karen Page", patientId: 15 },
  },
  Thursday: {
    "08:30": { patientName: "Leo King", patientId: 16 },
    "10:00": { patientName: "Mona Ray", patientId: 17 },
    "11:30": { patientName: "Nina West", patientId: 18 },
    "14:30": { patientName: "Oscar Wilde", patientId: 19 },
    "16:30": { patientName: "Paul Young", patientId: 20 },
  },
  Friday: {
    "09:00": { patientName: "Quinn Fox", patientId: 21 },
    "10:30": { patientName: "Rita Stone", patientId: 22 },
    "12:30": { patientName: "Steve Nash", patientId: 23 },
    "14:00": { patientName: "Tina Bell", patientId: 24 },
    "15:30": { patientName: "Uma Dale", patientId: 25 },
  },
};